language: node_js

node_js:
  - "stable"

env:
  - NODE_ENV="development"


services:
  - postgresql

dist: trusty
addons:
  postgresql: "10.4"

before_script:
  - psql -c 'drop database if exists ridesDB;' -U postgres
  - psql -c 'create database ridesDB;' -U postgres

script:
  - mocha --require babel-register

# safelist
branches:
  only:
  - master
  - gh-pages
