language: node_js

node_js:
  - "stable"

env:
  - NODE_ENV="development"


services:
  - postgresql

dist: trusty
sudo: required

addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
env:
  global:
  - PGPORT=5433

before_script:
  - sudo -u postgres psql -c 'drop database if exists ridesDB;' 
  - sudo -u postgres psql -c 'create database ridesDB;'

script:
  - mocha --require babel-register

# safelist
branches:
  only:
  - master
  - gh-pages
