language: node_js

node_js:
  - "stable"

sudo: false
dist: trusty 


services:
  - postgresql

addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10

env:
  global:
  - PGPORT=5433


script:
  - mocha --require babel-register

# safelist
branches:
  only:
  - master
  - gh-pages
