language: node_js

node_js:
  - "stable"

sudo: false
dist: trusty

services:
 - postgresql 

addons:
  apt:
    packages:
      - postgresql-10
      - postgresql-client-10
  postgresql: "10"

env:
  global:
    - PGPORT=5433

before_script:
  - psql -c "ALTER USER travis WITH PASSWORD 'travis';"
  - psql -c "CREATE DATABASE travis WITH OWNER = travis;"



script:
  - mocha --require babel-register

# safelist
branches:
  only:
  - master
  - gh-pages
