language: node_js

node_js:
  - "stable"

os: linux
sudo: true
dist: trusty 


services:
  - postgresql

addons:
  postgresql: "10"  # I'm just using this, if you're using another version, might need to fix the pg_hba.conf path below
before_install:
  # stop old version
  - sudo /etc/init.d/postgresql stop
  # add postgresql 10 repository
  - wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
  - sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -cs 2>/dev/null)-pgdg main" >> /etc/apt/sources.list.d/postgresql.list'
  # install new version
  - sudo apt-get update -qq
  - sudo apt-get install -qq postgresql-10 postgresql-client-10
  # clone auth config (might need to fix source path for another version)
  - sudo cp /etc/postgresql/9.6/main/pg_hba.conf /etc/postgresql/10/main/pg_hba.conf
  - sudo sed -i 's/port = 5433/port = 5432/' /etc/postgresql/10/main/postgresql.conf
  # start new version
  - sudo /etc/init.d/postgresql restart


before_script:
  - psql -c "ALTER USER travis WITH PASSWORD 'travis';"
  - sudo -u postgres psql -c "CREATE DATABASE travis;"

script:
  - mocha --require babel-register

# safelist
branches:
  only:
  - master
  - gh-pages
