language: node_js

node_js:
  - "stable"

sudo: true
dist: trusty 


services:
  - postgresql

addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
  env:
    global:
    - PGPORT=5433

postgres:
  adapter: postgresql
  database: travis_ci_test
  username: postgres

before_script:
    - sudo -u postgres psql -c "CREATE DATABASE ridesDB;"
    - rake db:migrate

script:
  - mocha --require babel-register

# safelist
branches:
  only:
  - master
  - gh-pages
