language: node_js

node_js:
  - "stable"

dist: trusty 
sudo: required

services:
  - postgresql

addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10

env:
  global:
  - PGPORT=5433
  - DATABASE_DEVELOPMENT_URL=postgres://postgres@127.0.0.1:5432/travis
  - DATABASE_TEST_URL=postgres://postgres@127.0.0.1:5432/ronke
  - SECRET_KEY='3377'


before_script:
  - sudo -u postgres psql -c 'drop database if exists ridesDB;' 
  - sudo -u postgres psql -c 'create database ridesDB;' 

script:
  - mocha --require babel-register

# safelist
branches:
  only:
  - master
  - gh-pages
