os: osx
language: node_js

node_js:
  - "stable"

sudo: false
dist: trusty

Services:
 - postgresql 10.4

addons:
  apt:
    packages:
      - postgresql-10
      - postgresql-client-10
  postgresql: "10"
env:
  global:
    - PGPORT=5433
before_script:
  - psql -c "ALTER USER travis WITH PASSWORD 'travis';"
  - psql -c "CREATE DATABASE ridesDB;"



script:
  - mocha --require babel-register

# safelist
branches:
  only:
  - master
  - gh-pages
