language: node_js

node_js:
  - "stable"

env:
  - NODE_ENV="development"


services:
  - postgresql

dist: trusty
sudo: required

addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10

before_script:
  - psql -c 'drop database if exists ridesDB;' -U postgres
  - psql -c 'create database ridesDB;' -U postgres

script:
  - mocha --require babel-register

# safelist
branches:
  only:
  - master
  - gh-pages
