language: node_js

node_js:
  - "stable"

services:
  - postgresql

script:
  - mocha --compilers js:babel-register

cache:
  directories:
    - "node_modules"

# safelist
branches:
  only:
  - master
  - gh-pages