language: node_js

node_js:
  - "stable"

env:
  - NODE_ENV="development"


services:
  - postgresql

sudo: false
dist: trusty

addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
env:
  global:
  - PGPORT=5433

before_script:
  - psql -c "ALTER USER travis WITH PASSWORD 'travis';"

script:
  - mocha --require babel-register

# safelist
branches:
  only:
  - master
  - gh-pages
