language: node_js

node_js:
  - "stable"

sudo: true
dist: trusty 


services:
  - postgresql

addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10

env:
  global:
    - DB_USER_TEST=postgres
    - DB_HOST_TEST=localhost
    - DB_NAME_TEST=ridesDB
    - DB_PASSWORD_TEST=3377
    - DB_PORT_TEST=5432

before_script:
    # Use default port
    - sudo sed -i 's/port = 5433/port = 5432/' /etc/postgresql/10/main/postgresql.conf
    # Use 9.6 auth config:
    - sudo cp /etc/postgresql/{9.6,10}/main/pg_hba.conf
    - sudo service postgresql restart
    - sudo -u postgres psql -c "CREATE DATABASE ridesDB;"  

script:
  - mocha --require babel-register

# safelist
branches:
  only:
  - master
  - gh-pages
