language: node_js

node_js:
  - "node"

sudo: true
dist: trusty 


services:
  - postgresql

addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10

before_script:
    # Use default port
    - sudo sed -i 's/port = 5433/port = 5432/' /etc/postgresql/10/main/postgresql.conf
    # Use 9.6 auth config:
    - sudo cp /etc/postgresql/{9.6,10}/main/pg_hba.conf
    - sudo sed -i -e '/local.*peer/s/postgres/all/' -e 's/peer\|md5/trust/g' /etc/postgresql/*/main/pg_hba.conf
    - sudo service postgresql restart
    - sleep 1
    - sudo -u postgres psql -c "CREATE DATABASE ridesDB;"  

script:
  - mocha --require babel-register

# safelist
branches:
  only:
  - master
  - gh-pages
