language: node_js

node_js:
  - "stable"

env:
  - NODE_ENV="development"


services:
  - postgresql

before_script:
  - psql -c 'drop database if exists ridesDB;' -U postgres
  - psql -c 'create database ridesDB;' -U postgres

# safelist
branches:
  only:
  - master
  - gh-pages

cache:
  directories:
    - "node_modules"