language: node_js

node_js:
  - "stable"

sudo: true
dist: xenial 


services:
  - postgresql

addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10



before_script:
  - sudo -u postgres psql -c "CREATE USER ronke PASSWORD '3377';"
  - sudo -u postgres psql -c 'create database ridesDB;' 

script:
  - mocha --require babel-register

# safelist
branches:
  only:
  - master
  - gh-pages
