language: node_js

node_js:
  - "stable"

dist: trusty 
sudo: required

env:
  global:
  - PGPORT=5433


services:
  - postgresql

addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10


before_script:
  - psql -c 'drop database if exists ridesDB;' -U postgres
  - psql -c 'create database ridesDB;' -U postgres

script:
  - mocha --require babel-register

# safelist
branches:
  only:
  - master
  - gh-pages
