language: node_js

node_js:
  - "stable"

dist: trusty 
sudo: required

services:
  - postgresql

addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10

env:
  global:
  - PGPORT=5433


before_script:
  - psql -c "ALTER USER travis WITH PASSWORD 'travis';"
  - sudo -u postgres psql -c 'create database ridesDB;' 

script:
  - mocha --require babel-register

# safelist
branches:
  only:
  - master
  - gh-pages
